# Generated by Django 3.1.7 on 2021-03-15 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='closed_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='created_at',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='qualifications',
            field=models.ManyToManyField(blank=True, related_name='qualified_users', to='api.Qualification'),
        ),
        migrations.AlterField(
            model_name='user',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='skilled_users', to='api.Skill'),
        ),
    ]
