# Generated by Django 3.1.7 on 2021-04-05 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210323_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualification',
            name='institution',
            field=models.CharField(default='__uninformed__', max_length=255),
        ),
        migrations.AddField(
            model_name='qualification',
            name='time_course',
            field=models.IntegerField(default=0),
        ),
    ]
